### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by dlin345** [Where-To-Meet/Where-To-Meet.github.io#10]
![selection_011](https://cloud.githubusercontent.com/assets/10427548/25927880/d504972c-35ad-11e7-9f75-762c94200947.png)

**Comment by nan2iz** [comment]
Phototype for homework3 reference

![screen shot 2017-05-10 at 6 39 38 pm](https://cloud.githubusercontent.com/assets/17581141/25928276/2d35e7c8-35b0-11e7-9a95-47d8f5c5b544.png)
